# Create a Jekyll container from a Ruby Alpine image

# At a minimum, use Ruby 2.5 or later
#FROM ruby:latest
#FROM alpine:latest
# At a minimum, use Ruby 2.5 or later
#FROM ruby:2.7-alpine3.16
FROM ruby:alpine3.17

# Add Jekyll dependencies to Alpine
RUN apk update
RUN apk add --no-cache build-base gcc cmake git

RUN gem update --system 
RUN gem install jekyll bundler
RUN gem cleanup

EXPOSE 4000
EXPOSE 35729

VOLUME [ "/site", "/usr/local/bundle" ]

WORKDIR /site

CMD ["jekyll", "--help"]

